### PR TITLE
Improve class search performance

### PR DESCRIPTION
**Pull request by not-rusty**
Hello!

I took a look at your cheatsheet, and while it has a good UI, the search performance is awful. This commit just prevents searching when the input size is less than 4 characters.

My reasoning is that when I'm using the cheatsheet, I know for sure the property I'm looking for, so I'll type "width", or "height". Now, the first three characters will trigger 3 searches across a huge js object (the cheatsheet.json weights 748kb on my machine). I would argue that those first 3 searches are a waste. If I'm looking for "font family" and I write "fo", many Flexbox & Grid components appear, even thought I'm certain I'm not looking for those.

This doesn't really address the big issue, why on earth is a rerender that expensive. I tried to look at how could I optimize the whole rerendering (for fun), but if I want to preserve the current search UX I did not have much luck, React memo did not help much here. I don't think it is a lost cause, but it is a bit more difficult than "just use useMemo and be done".

### CODE REVIEW

**Comment by m-atthart** [comment]
you're right, the search performance is pretty bad, but i don't think this is necessarily the right solution. at least in my experience, typing two or three letters usually cuts down the page enough for me to find what i'm looking for.

the first thing i thought of was to have the search behind a settimeout, and have the settimeout reset on input change, so that the search only happens once: when the user is done typing. but after playing with the site, the search seems to speed up as the remaining number of options decreases (it's only searching across the results that remain).

so taking all that into consideration, what if we put our solutions together, and have the search happen immediately if the input is >=4 characters, and have a settimeout if the input is <4 characters?

or we can just do nothing about it, because in my testing, the site seems to complete the search anyway by the time i've typed 4 letters, and any characters after that update the search basically immediately.

**Comment by not-rusty** [comment]
> so taking all that into consideration, what if we put our solutions together, and have the search happen immediately if the input is >=4 characters, and have a settimeout if the input is <4 characters?

I like that solution! I did not think of that.

Doesn't seem hard to implement, I'll take a look at it.

**Comment by not-rusty** [comment]
> and have a settimeout if the input is <4 characters?

I did still notice significant lag when searching synchronously on 4 characters. As most css property names are longer than 4 chars, I did increase the sync search limit at 5 chars.

It's your repo, so your rules, we can agree at 4 nevertheless.

I did use 300ms as the artificial delay to adecuate to the lowest common denominator. Most programmers write between 50wpm to 80wpm, that delay did feel good enough for me.

**Comment by not-rusty** [comment]
> and have a settimeout if the input is <4 characters?

I did still notice significant lag when searching synchronously on 4 characters. As most css property names are longer than 4 chars, I did increase the sync search limit at 5 chars.

It's your repo, so your rules, we can agree at 4 nevertheless.

I did use 300ms as the artificial delay to adecuate to the lowest common denominator. Most programmers write between 50wpm to 80wpm, that delay did feel good enough for me.

**Comment by khatabwedaa** [comment]
@not-rusty, Thanks for your PR can you fix the conflicts after I merge #26, I got some conflicts and I think it's breaking your code.

**Comment by not-rusty** [comment]
Done!

**Pull request merged**
