### PR TITLE
Adding query param support for custom search engines in browsers

### LINKED ISSUE #50: Add query param support to URL
Lots of browsers support [Custom Search Engines](https://support.google.com/chrome/answer/95426?hl=en&co=GENIE.Platform%3DDesktop). This change would allow me to type "tw" -> hit tab -> and type in a search term, and then I could open the tailwind cheatsheet to the specific query I'm thinking of. It'd be a huge ergonomic win!

### PR DESCRIPTION
**Pull request by heysweet**
Resolves https://github.com/tailwindcomponents/cheatsheet/issues/50#issue-2158983583

Lots of browsers support [Custom Search Engines](https://support.google.com/chrome/answer/95426?hl=en&co=GENIE.Platform%3DDesktop). This change would allow me to type "tw" -> hit tab -> and type in a search term, and then I could open the tailwind cheatsheet to the specific query I'm thinking of. It'd be a huge ergonomic win!

I know that my implementation of this change isn't up to today's standards, but I didn't want to go through upgrading all of the packages to unlock `useSearchParams` from `react-router-dom` (I tried and found a few other dependencies on `history` that made this upgrade a larger swing than I wanted to take on.)

### CODE REVIEW

**Comment by heysweet** [comment]
I don't feel strongly about the tool versions or yarn lock changes if you want to toss them

**Comment by heysweet** [comment]
@khatabwedaa any chance you could take a look?

**Comment by khatabwedaa** [comment]
@heysweet, hey man sorry for not response, I'm soo busy last few months but I will check it now.

**Comment by khatabwedaa** [comment]
@heysweet I just text the PR thank you for your awesome work just one think I want you to remove the quarry form URL if it's empty 
Screenshot from 2024-06-26 20-52-56

**Comment by khatabwedaa** [comment]
Thanks for your awesome work @heysweet . 😄  I merged it I will deploy it today so you can check it live.

**Pull request merged**
